from enum import Enum

class ReviewStatus(Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    VERIFIED_WITH_CORRECTIONS = "VERIFIED_WITH_CORRECTIONS"
    REJECTED = "REJECTED"
    FAILED_PROCESSING = "FAILED_PROCESSING"
